import pytest
from unittest.mock import MagicMock, patch
import sys
import os

# Add the root directory to PYTHONPATH to resolve brain module imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))

from brain.decoder import EventDecoder

def test_decode_aave_borrow():
    with patch('brain.decoder.Web3'):
        decoder = EventDecoder()
        
        # Mock the Contract Event Process Log generated by Web3
        mock_event = {
            'address': '0x794a61358D6845594F94dc1DB02A252b5b4814aD', # Aave Pool
            'args': {
                'reserve': '0xaf88d065e77c8cc2239327c5edb3a432268e5831', # USDC
                'user': '0x1234567890abcdef1234567890abcdef12345678',
                'amount': 1000000
            }
        }
        
        # Deep mock the Web3 contract event pipeline
        decoder.aave_contract = MagicMock()
        decoder.aave_contract.events.Borrow.return_value.process_log.return_value = mock_event
        
        # Pass a dummy raw log to the decoder
        result = decoder.decode_aave_borrow({"dummy": "log"})
        
        assert result is not None
        assert result['type'] == 'BORROW'
        assert result['protocol'] == 'AAVE_V3'
        assert result['pool'] == mock_event['address'].lower()
        assert result['asset'] == mock_event['args']['reserve'].lower()
        assert result['user'] == mock_event['args']['user'].lower()
        assert result['amount'] == 1000000

def test_decode_aave_repay():
    with patch('brain.decoder.Web3'):
        decoder = EventDecoder()
        
        mock_event = {
            'address': '0x794a61358D6845594F94dc1DB02A252b5b4814aD',
            'args': {
                'reserve': '0xaf88d065e77c8cc2239327c5edb3a432268e5831',
                'user': '0x1234567890abcdef1234567890abcdef12345678',
                'amount': 500000
            }
        }
        
        decoder.aave_contract = MagicMock()
        decoder.aave_contract.events.Repay.return_value.process_log.return_value = mock_event
        
        result = decoder.decode_aave_repay({"dummy": "log"})
        
        assert result is not None
        assert result['type'] == 'REPAY'
        assert result['amount'] == 500000
        assert result['user'] == mock_event['args']['user'].lower()
